cursor            #d0bcfe
cursor_text_color #36265d

foreground            #e6e0e9
background            #0f0d13
selection_foreground  #332d41
selection_background  #ccc2db
url_color             #ccc2db

#: black 000000 767676
color0  #141218
color8  #36343a
#: red cc0403 f2201f
color1  #a56ca5
color9  #dfcbdf
#: green 19cb00 23fd00
color2  #ccc2db
color10 #e8def8
#: yellow cecb00 fffd00
color3  #efb8c7
color11 #ffd9e2
#: blue 0d73cc 1a8fff
color4  #4d3d75
color12 #d0bcfe
#: magenta cb1ed1 fd28ff
color5  #4a4458
color13 #ccc2db
#: cyan 0dcdcd 14ffff
color6  #633b48
color14 #efb8c7
#: white dddddd ffffff
color7  #cac4cf
color15 #e6e0e9

mark1_foreground #210f47
mark1_background #e9ddff
mark2_foreground #1e192b
mark2_background #e8def8
mark3_foreground #31101d
mark3_background #ffd9e2

active_tab_foreground #36265d
active_tab_background #d0bcfe
inactive_tab_foreground #e9ddff
inactive_tab_background #4d3d75

active_border_color #d0bcfe
inactive_border_color #36265d
# bell_border_color #ff5a00
